# Main Navigation Menu

[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "About"
  identifier = "about"
  weight = 20

[[main]]
  parent = "about"
  name = "Mission & Values"
  url = "about/mission/"
  weight = 21

[[main]]
  parent = "about"
  name = "Board of Directors"
  url = "about/board/"
  weight = 22

[[main]]
  parent = "about"
  name = "Programs"
  url = "about/programs/"
  weight = 23

[[main]]
  parent = "about"
  name = "Curriculum"
  url = "about/curriculum/"
  weight = 24

[[main]]
  name = "News"
  url = "news/"
  weight = 50

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 60
